{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dta-agent-platform.secretName" . }}
  labels:
    {{- include "dta-agent-platform.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secret.values }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
